In [42]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [43]:
import pandas as pd
import numpy as np

In [44]:
df_gameplaydata = pd.read_csv('/content/drive/MyDrive/Project Data Analyst/gameplay_data.csv', encoding='UTF-8', index_col=0)
df_sessiondata = pd.read_csv('/content/drive/MyDrive/Project Data Analyst/sessions_data.csv', encoding='UTF-8', index_col=0)
df_userdata = pd.read_csv('/content/drive/MyDrive/Project Data Analyst/users_data.csv', encoding='UTF-8', index_col=0)
df_transactiondata = pd.read_csv('/content/drive/MyDrive/Project Data Analyst/transactions_data.csv', encoding='UTF-8', index_col=0)

In [45]:
df_gameplaydata.info()
df_sessiondata.info()
df_userdata.info()
df_transactiondata.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7000 entries, 0 to 6999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         7000 non-null   int64
 1   user_id          7000 non-null   int64
 2   event_type       7000 non-null   object
 3   event_time       7000 non-null   object
 4   level_completed  7000 non-null   int64
 5   event_day        7000 non-null   int64
 6   event_month      7000 non-null   int64
 7   event_year       7000 non-null   int64
dtypes: int64(6), object(2)
memory usage: 492.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   session_id  5000 non-null   int64
 1   user_id     5000 non-null   int64
 2   start_time  5000 non-null   object
 3   end_time    5000 non-null   object
 4   device      5000 non-null   object
dtypes: int64(2), object(3)
memory usage: 234.4+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       1000 non-null   int64
 1   country       1000 non-null   object
 2   device        1000 non-null   object
 3   signup_date   1000 non-null   object
 4   signup_day    1000 non-null   int64
 5   signup_month  1000 non-null   int64
 6   signup_year   1000 non-null   int64
dtypes: int64(4), object(3)
memory usage: 62.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   2000 non-null   int64
 1   user_id          2000 non-null   int64
 2   item_purchased   2000 non-null   object
 3   purchase_amount  2000 non-null   float64
 4   purchase_date    2000 non-null   object
 5   purchase_day     2000 non-null   int64
 6   purchase_month   2000 non-null   int64
 7   purchase_year    2000 non-null   int64
dtypes: float64(1), int64(5), object(2)
memory usage: 140.6+ KB

In [46]:
df_gameplaydata.isna()
df_sessiondata.isna()
df_userdata.isna()
df_transactiondata.isna()

,transaction_id,user_id,item_purchased,purchase_amount,purchase_date,purchase_day,purchase_month,purchase_year
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False

In [47]:
df_gameplaydata.isnull()
df_sessiondata.isnull()
df_userdata.isnull()
df_transactiondata.isnull()

,transaction_id,user_id,item_purchased,purchase_amount,purchase_date,purchase_day,purchase_month,purchase_year
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False

In [48]:
df_gameplaydata['event_day']=pd.to_datetime(df_gameplaydata['event_time'], format='%Y-%m-%d').dt.day
df_gameplaydata['event_month']=pd.to_datetime(df_gameplaydata['event_time'], format='%Y-%m-%d').dt.month
df_gameplaydata['event_year']=pd.to_datetime(df_gameplaydata['event_time'], format='%Y-%m-%d').dt.year
df_transactiondata['purchase_day']=pd.to_datetime(df_transactiondata['purchase_date'], format='%Y-%m-%d').dt.day
df_transactiondata['purchase_month']=pd.to_datetime(df_transactiondata['purchase_date'], format='%Y-%m-%d').dt.month
df_transactiondata['purchase_year']=pd.to_datetime(df_transactiondata['purchase_date'], format='%Y-%m-%d').dt.year
df_userdata['signup_day']=pd.to_datetime(df_userdata['signup_date'], format='%Y-%m-%d').dt.day
df_userdata['signup_month']=pd.to_datetime(df_userdata['signup_date'], format='%Y-%m-%d').dt.month
df_userdata['signup_year']=pd.to_datetime(df_userdata['signup_date'], format='%Y-%m-%d').dt.year

In [49]:
df_dtanalyst = pd.merge(df_transactiondata, df_userdata, on='user_id')

In [50]:
df_dtanalyst = pd.merge(df_dtanalyst, df_gameplaydata, on='user_id')

In [51]:
df_dtanalyst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13907 entries, 0 to 13906
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   13907 non-null  int64
 1   user_id          13907 non-null  int64
 2   item_purchased   13907 non-null  object
 3   purchase_amount  13907 non-null  float64
 4   purchase_date    13907 non-null  object
 5   purchase_day     13907 non-null  int32
 6   purchase_month   13907 non-null  int32
 7   purchase_year    13907 non-null  int32
 8   country          13907 non-null  object
 9   device           13907 non-null  object
 10  signup_date      13907 non-null  object
 11  signup_day       13907 non-null  int32
 12  signup_month     13907 non-null  int32
 13  signup_year      13907 non-null  int32
 14  event_id         13907 non-null  int64
 15  event_type       13907 non-null  object
 16  event_time       13907 non-null  object
 17  level_completed  13907 non-null  int64
 18  event_day        13907 non-null  int32
 19  event_month      13907 non-null  int32
 20  event_year       13907 non-null  int32
dtypes: float64(1), int32(9), int64(4), object(7)
memory usage: 1.8+ MB

In [52]:
#Quoc gia co so luong nguoi choi nhieu nhat
df_userdata.groupby('country')['user_id'].count().sort_values(ascending=False).head()

country
US    223
VN    207
IN    195
JP    189
CA    186
Name: user_id, dtype: int64

In [53]:
#Loai vat pham duoc mua nhieu nhat
df_dtanalyst['item_purchased'].value_counts().head()

item_purchased
Gems            4885
Subscription    4584
Coins           4438
Name: count, dtype: int64

In [54]:
#Doanh thu cao nhat trong thang 5 den tu quoc gia nao
df_dtanalyst[df_dtanalyst['purchase_month']==5].groupby('country')['purchase_amount'].sum().sort_values(ascending=False).head()

country
US    19190.91
VN    17954.42
JP    16950.25
CA    15844.60
IN    12375.86
Name: purchase_amount, dtype: float64

In [63]:
#Nguoi choi chi tieu tien nhieu nhat la ai va level_completed ho dat duoc la bao nhieu
df1 = df_dtanalyst.groupby('user_id')['purchase_amount'].sum().sort_values(ascending=False)
df2 = df_dtanalyst.groupby('user_id')['level_completed'].max().sort_values(ascending=False)
df3 = pd.merge(df1, df2, on='user_id')
df4 = pd.merge(df3, df_userdata, on='user_id')
df4 = df4[['user_id', 'purchase_amount', 'level_completed', 'country', 'device']]
df4.to_csv('/content/drive/MyDrive/Project Data Analyst/data.csv')
df4.info()
df4.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          864 non-null    int64
 1   purchase_amount  864 non-null    float64
 2   level_completed  864 non-null    int64
 3   country          864 non-null    object
 4   device           864 non-null    object
dtypes: float64(1), int64(2), object(2)
memory usage: 33.9+ KB

   user_id  purchase_amount  level_completed country   device
0      511          3783.15               39      VN  Android
1      982          3538.59               43      CA       PC
2       92          3449.10               45      JP       PC
3      106          3209.52               46      JP       PC
4      257          3200.67               49      IN       PC
5      858          3151.32               48      JP      iOS
6      967          3061.08               48      VN       PC
7      256          2984.41               42      IN      iOS
8      628          2972.00               50      IN  Android
9      160          2944.26               48      CA      iOS

In [62]:
#Ty le phan tram nguoi choi con choi sau 30 ngay
df5 = df_dtanalyst.groupby('user_id')['event_time'].max()
df5 = pd.DataFrame(df5)
df5.columns = ['event_time_last']
df5 = pd.merge(df5, df_userdata, on='user_id')
df5['Number_of_days_played'] = (pd.to_datetime(df5['event_time_last']) - pd.to_datetime(df5['signup_date'])).dt.days
df5.to_csv('/content/drive/MyDrive/Project Data Analyst/data_tylengchoi.csv')
df5 = df5[df5['Number_of_days_played'] > 30]
df5.info()
tlccs30n = df5['user_id'].count() / df_userdata['user_id'].count() * 100
print(f'Ty le % nguoi con choi sau 30 ngay la: {tlccs30n}%')

<class 'pandas.core.frame.DataFrame'>
Index: 631 entries, 1 to 863
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                631 non-null    int64
 1   event_time_last        631 non-null    object
 2   country                631 non-null    object
 3   device                 631 non-null    object
 4   signup_date            631 non-null    object
 5   signup_day             631 non-null    int32
 6   signup_month           631 non-null    int32
 7   signup_year            631 non-null    int32
 8   Number_of_days_played  631 non-null    int64
dtypes: int32(3), int64(2), object(4)
memory usage: 41.9+ KB
Ty le % nguoi con choi sau 30 ngay la: 63.1%

In [57]:
#Du doan doanh thu moi nguoi choi dua tren purchase_amount, level_completed, country, device su dung mo hinh LinearRegression
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

In [58]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          864 non-null    int64
 1   purchase_amount  864 non-null    float64
 2   level_completed  864 non-null    int64
 3   country          864 non-null    object
 4   device           864 non-null    object
dtypes: float64(1), int64(2), object(2)
memory usage: 33.9+ KB

In [59]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
df4['country'] = lb_make.fit_transform(df4['country'])
df4['device'] = lb_make.fit_transform(df4['device'])
df4.head()

   user_id  purchase_amount  level_completed  country  device
0      511          3783.15               39        4       0
1      982          3538.59               43        0       1
2       92          3449.10               45        2       1
3      106          3209.52               46        2       1
4      257          3200.67               49        1       1

In [60]:
features = ['country', 'device', 'level_completed']
target = ['purchase_amount']
X = df4[features]
y = df4[target]
#Chia bo du lieu thanh hai tap train, test 90% train, 10%test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [61]:
#Huan luyen mo hinh
model = LinearRegression()
model.fit(X_train, y_train)
#Du doan doanh thu
y_pred = model.predict(X_test)
#Danh gia mo hinh
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 342728.8478981223